name: Run Hoxhunt Web Scrape Extract and Load to Raw

on:
  schedule:
    - cron: '0 8 1 2 *'  # once a year on February 1st at 8 AM UTC
  workflow_dispatch:     # allow manual trigger

env:
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_PORT: ${{ secrets.PG_PORT }}
  PG_DB: ${{ secrets.PG_DB }}

jobs:
  extract_load_raw:
    name: Run Hoxhunt Web Scrape Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install python dependencies
        working-directory: ${{ github.workspace }}
        run: |
          pip install -r requirements.txt

      - name: Run Hoxhunt Web Scrape Extract/Load Script
        working-directory: notebooks
        run: |
          python HoxHunt_Web_Scrape_Extract_Load_Raw.py

      
      
