name: Run PhishTank API Extract and Load to Raw

on:
  schedule:
    - cron: '0 7 * * *'  # runs daily at 7:00 AM UTC (midnight PDT)
  workflow_dispatch:     # allows manual trigger

env:
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_DB: ${{ secrets.PG_DB }}

jobs:
  extract_load_raw:
    name: Run PhishTank API Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PhishTank API Extract/Load Script
        run: python notebooks/PhishTank_API_Extract_Load_Raw.py

